tp/apps/requ/urls.py
from django.urls import path
from . import views

app_name = "requ"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/comment', views.comment, name='comment'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('sysadmin/', views.admin, name='admin'),
    path('user/', views.user, name='user'),
    path('profile/', views.profile, name="profile"),
    path('<int:id>/solved', views.solved, name="solved"),
    path('back/', views.back, name="back"),
    path('new_request', views.new_request, name="new_request"),
    path('<int:id>/unsolved', views.unsolved, name="unsolved"),
]

tp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('requ.urls')),
    path('admin/', admin.site.urls)
]

tp/apps/requ/models.py
from django.contrib.auth.models import User
from django.db import models


class Request(models.Model):
    text = models.TextField('Текст заявки')
    is_solved = models.BooleanField('Проблема решена')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    solver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='solver', blank=True, null=True)
    pub_date = models.DateTimeField('дата публикации')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'


class Comment(models.Model):
    text = models.CharField('текст комментария', max_length=255)
    request = models.ForeignKey(Request, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

tp/apps/requ/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

tp/apps/requ/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render

from .forms import LoginForm
from .models import Request, Comment
from django.http import Http404, HttpResponseRedirect, HttpResponse
from datetime import datetime


def index(request):
    return render(request, 'requ/index.html', {'is_auth': request.user.is_authenticated})


def comment(request, id):
    try:
        a = Request.objects.get(id=id)
    except:
        raise Http404("Заявка не найдена!")

    c = Comment(text=request.POST['text'], author=request.user, request=a)
    c.save()
    return HttpResponseRedirect('/' + str(id))


def detail(request, id):
    try:
        req = Request.objects.get(id=id)
        user_ = request.user
        if user_.groups.filter(name="sysadm").exists() or user_.is_superuser or user_ == req.author:
            comments = Comment.objects.filter(request=req)
        else:
            return HttpResponse("Недостаточно прав!")
    except:
        raise Http404("Заявка не найдена!")
    return render(request, 'requ/detail.html', {'req': req, 'comments': comments})


def log_in(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user_ = authenticate(username=cleaned_data['username'], password=cleaned_data['password'])
            if user_ is not None:
                if user_.is_active:
                    login(request, user_)
                    if user_.groups.filter(name='user').exists():
                        return HttpResponseRedirect('/user/')
                    if user_.groups.filter(name='sysadm').exists():
                        return HttpResponseRedirect('/sysadmin/')
                else:
                    return render(request, 'requ/login.html', {'error': 'disabled'})
            else:
                return render(request, 'requ/login.html', {'error': 'invalid'})
    return render(request, 'requ/login.html', {'is_auth': request.user.is_authenticated,
                                               'user': request.user})


def log_out(request):
    logout(request)
    return HttpResponseRedirect('/login/')


def user(request):
    reqs = Request.objects.order_by('-pub_date').filter(author=request.user)
    if request.user.groups.filter(name='user').exists() or request.user.is_superuser:
        return render(request, 'requ/user.html', {'reqs': reqs})
    else:
        return HttpResponse('Недостаточно прав')


def admin(request):
    reqs = Request.objects.order_by('-pub_date').filter(is_solved=False)
    if request.user.groups.filter(name='sysadm').exists() or request.user.is_superuser:
        return render(request, 'requ/admin.html', {'reqs': reqs})
    else:
        return HttpResponse('Недостаточно прав')


def new_request(request):
    if request.method == "POST":
        r = Request(text=request.POST['text'], author=request.user, is_solved=False,
                    pub_date=datetime.now())
        r.save()
        print(r)
        return HttpResponseRedirect('/back/')
    else:
        return render(request, "requ/new_request.html", {'is_auth': request.user.is_authenticated})


def profile(request):
    user_ = request.user
    if user_.is_authenticated:
        if user_.groups.filter(name="sysadm").exists():
            status = "Системный администратор"
        elif user_.groups.filter(name="user").exists():
            status = "Пользователь"
        elif user_.is_superuser:
            status = "Админ"
        else:
            status = "Другое"
        return render(request, 'requ/profile.html', {'user': user_, 'status': status})
    else:
        return HttpResponseRedirect('/login/')


def solved(request, id):
    a = Request.objects.get(id=id)
    a.solver = request.user
    a.is_solved = True
    a.save()
    return HttpResponseRedirect('/' + str(id))


def unsolved(request, id):
    a = Request.objects.get(id=id)
    a.solver = None
    a.is_solved = False
    a.save()
    return HttpResponseRedirect('/' + str(id))


def back(request):
    user_ = request.user
    if user_.groups.filter(name='user').exists():
        return HttpResponseRedirect('/user/')
    elif user_.groups.filter(name='sysadm').exists():
        return HttpResponseRedirect('/sysadmin/')
    elif user_.is_superuser:
        return HttpResponseRedirect('/sysadmin/')
    else:
        return HttpResponseRedirect('/login/')

tp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>{% block tittle %}Тех поддержка{% endblock %}</title>
</head>
<body>
<nav>
    <div class="nav-wrapper teal darken-3">
        <a href="{% url "requ:index" %}" class="brand-logo"><i class="material-icons">home</i>Главная</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url "requ:profile" %}"><i class="material-icons">person</i></a></li>
            <li><a href="{% url "requ:back" %}"><i class="material-icons">list</i></a></li>
        </ul>
    </div>
</nav>

<ul id="mobile-demo" class="sidenav">
    <li><a href="{% url "requ:profile" %}">Аккаунт</a></li>
    <li><a href="{% url "requ:back" %}">Заявки</a></li>
</ul>

<main>
    {% block content %}{% endblock %}
</main>
<style>
    @media (max-width: 575px) {
        main {
            margin: 0 3px;
        }
    }

    @media (min-width: 576px) and (max-width: 767px) {
        main {
            margin: 0 7px;
        }
    }

    @media (min-width: 768px) and (max-width: 991px) {
        main {
            margin: 0 60px;
        }
    }

    @media (min-width: 992px) and (max-width: 1199px) {
        main {
            margin: 0 120px;
        }
    }

    @media (min-width: 1200px) {
        main {
            margin: 0 300px;
        }
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    $( document ).ready(function(){
        $('.sidenav').sidenav();
        $(".dropdown-trigger").dropdown({ hover: true });
      });
</script>
</body>
</html>

tp/templates/requ/admin.html
{% extends 'base.html' %}

{% block tittle %}Заявки{% endblock %}

{% block content %}
    {% if reqs %}
        <h3 class="center-align">Последние не решенные заявки</h3>
        <div class="row">
            {% for a in reqs %}
                <div class="col s12 m6">
                    <div class="card teal darken-4 hoverable">
                        <div class="card-content white-text">
                            <span class="card-title">{{ a.pub_date }}</span>
                            <p class="truncate">{{ a.text }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'requ:detail' a.id %}">Подробнее</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

tp/templates/requ/detail.html
{% extends 'base.html' %}

{% block tittle %}Заявка{% endblock %}

{% block content %}
    <h4 class="center-align">Заявка</h4>
    <div class="row center-aligned">
        <table class="striped">
            <tr>
                <td>Заявитель</td>
                <td>{{ req.author }}</td>
            </tr>
            <tr>
                <td>Проблема</td>
                <td>{{ req.text }}</td>
            </tr>
            {% if req.is_solved %}
                <tr>
                    <td>Проблема</td>
                    <td><i class="material-icons">done</i>Решена</td>
                </tr>
                {% if req.solver %}
                    <tr>
                        <td>Решил</td>
                        <td>{{ req.solver }}</td>
                    </tr>
                {% endif %}
            {% else %}
                <tr>
                    <td>Проблема</td>
                    <td><i class="material-icons">close</i>Не решена</td>
                </tr>
            {% endif %}
            <tr>
                <td><i class="material-icons">access_time</i></td>
                <td>{{ req.pub_date }}</td>
            </tr>
        </table>
    </div>
    {% if req.is_solved %}
        <form action="{% url 'requ:unsolved' req.id %}">
            <button type="submit" class="waves-effect waves-light btn">
                <i class="material-icons left">disabled_by_default</i>Не решено
            </button>
        </form>
    {% else %}
        <form action="{% url 'requ:solved' req.id %}">
            <button type="submit" class="waves-effect waves-light btn">
                <i class="material-icons left">check</i>Решено
            </button>
        </form>
    {% endif %}
    <h4 class="center-align">Комментарии</h4>
    <table>
        {% for i in comments %}
            <tr>
                <td><i class="material-icons">person</i>{{ i.author }}</td>
                <td>{{ i.text }}</td>
            </tr>
        {% endfor %}
    </table>
    <form action="{% url 'requ:comment' req.id %}" method="post">
        {% csrf_token %}
        <div class="input-field">
            <input type="text" required name="text" id="text" class="validate">
            <label for="text">Комментарий</label>
        </div>
        <button type="submit" class="waves-effect waves-light btn">
            <i class="material-icons left">send</i>Отправить
        </button>
    </form>
{% endblock %}

tp/templates/requ/index.html
{% extends 'base.html' %}

{% block tittle %}Привет{% endblock %}

{% block content %}
    <style>
        body {
            backdrop-filter: blur(5px);
            background: url("https://www.intex-press.by/wp-content/uploads/2019/03/aaaaaaaaaaaaaa.jpg") no-repeat fixed;
            background-size: cover;
        }

        h5 {
            height: 1500px;
        }

        .btn-then {
            position: relative;
            bottom: 1300px;
            margin: auto;
        }
    </style>
    <h5 class="white-text">Привет! Мы - сервис, позволяющий удобно взаимодействовать системным администраторам и
        пользователям
        по вопросам технической поддержки</h5>
    {% if not is_auth %}
        {#        <p>Если тебе не выдал логин и пароль твой руководитель - напиши ему</p>#}
        <a href="{% url "requ:login" %}" class="waves-effect waves-light btn btn-then">
            <i class="material-icons left">login</i>
            Войти</a>
    {% else %}
        <a href="{% url "requ:back" %}" class="waves-effect waves-light btn btn-then">
            <i class="material-icons left">list</i>
            К заявкам</a>
    {% endif %}
{% endblock %}

tp/templates/requ/login.html
{% extends 'base.html' %}

{% block tittle %}Авторизация{% endblock %}

{% block content %}
    {% if is_auth %}
        <p>Вы вошли систему под аккаунтом {{ user }}</p>
        <a href="{% url "requ:logout" %}">Выйти</a>
    {% endif %}
    <form action="{% url 'requ:login' %}" method="POST" class="collection">
        {% csrf_token %}
        {% if error == "disabled" %}
            <p>Ваш аккаунт не активен</p>
        {% endif %}
        {% if error == "invalid" %}
            <p>Неверные данные</p>
        {% endif %}
        <input type="text" required placeholder="Логин" name="username" class="collection-item">
        <input type="password" required placeholder="Пароль" name="password" class="collection-item">
        <button type="submit" class="waves-effect waves-light btn"><i class="material-icons left">login</i>Войти
        </button>

    </form>
{% endblock %}

tp/templates/requ/new_request.html
{% extends 'base.html' %}

{% block tittle %}Авторизация{% endblock %}

{% block content %}

    {% if is_auth %}
        <h4 class="center-align">Заявка</h4>
        <form action="{% url 'requ:new_request' %}" method="POST">
            {% csrf_token %}
            <div class="input-field">
                <input type="text" required name="text" id="text" class="validate">
                <label for="text">Опишите вашу проблему</label>
            </div>
            <button type="submit" class="waves-effect waves-light btn">
                <i class="material-icons left">send</i>Отправить
            </button>
        </form>
    {% else %}
        <p> Вы не вошли в аккаунт </p>
    {% endif %}
{% endblock %}

tp/templates/requ/profile.html
{% extends 'base.html' %}

{% block tittle %}Профиль{% endblock %}

{% block content %}
    <h4 class="center-align">Профиль</h4>
    <table class="highlight striped">
        <tr>
            <td>Логин</td>
            <td>{{ user }}</td>
        </tr>
        {% if user.first_name %}
            <tr>
                <td>Имя</td>
                <td>{{ user.first_name }}</td>
            </tr>
        {% endif %}
        {% if user.last_name %}
            <tr>
                <td>Фамилия</td>
                <td>{{ user.last_name }}</td>
            </tr>
        {% endif %}
        {% if user.email %}
            <tr>
                <td>email</td>
                <td>{{ user.email }}</td>
            </tr>
        {% endif %}
        <tr>
            <td>Статус</td>
            <td>{{ status }}</td>
        </tr>
        <tr>
            <td>Действия</td>
            <td>
                <a href="{% url "requ:logout" %}"
                   class="waves-effect red darken-4 btn-small">
                    <i class="material-icons right">logout</i>Выйти</a>
            </td>
        </tr>
    </table>
{% endblock %}

tp/templates/requ/user.html
{% extends 'base.html' %}

{% block tittle %}Заявки{% endblock %}

{% block content %}
    {% if reqs %}
        <h3 class="center-align">Мои заявки</h3>
        <div class="row">
            {% for a in reqs %}
                <div class="col s12 m6">
                    <div class="card teal darken-4 hoverable">
                        <div class="card-content white-text">
                            <span class="card-title">{{ a.pub_date }}</span>
                            <p class="truncate">{{ a.text }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'requ:detail' a.id %}">Подробнее</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    {% endif %}
    <a href="{% url "requ:new_request" %}" class="btn-floating btn-large cyan pulse right-aligned">
        <i class="material-icons">add</i></a>
{% endblock %}